name: todo_app
description: "Responsive Flutter Todo App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_lints: ^6.0.0
  flutter_adaptive_scaffold: ^0.3.3+1
  go_router: ^16.2.2
  uuid: ^4.5.1
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  shimmer_animation: ^2.2.2
  json_serializable: ^6.11.1
  json_annotation: ^4.9.0
  build_runner: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true